name: k6 Load Test

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1  
        with: 
          path: performance-tests/test/src/test.js
          flags: --http-debug="full"
        env:
          YTENVIRONMENT: ${{ secrets.YTENVIRONMENT }}
          tokengenuser: ${{ secrets.TOKENGENUSER }}
          tokengenuserpwd: ${{ secrets.TOKENGENPWD }}
          userid: ${{ secrets.USERID }}
          partyid: ${{ secrets.PARTYID }}
          ssn: ${{ secrets.SSN }}
          serviceowner: ${{ secrets.OWNER }}
          K6_LOG_OUTPUT: stdout
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: summary-text
          path: performance-tests/test/src/stdout.txt
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: summary-html
          path: performance-tests/test/src/summary.html
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: summary-json
          path: performance-tests/test/src/summary.json
