name: k6 Load Test

on:
  push:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest
    container: docker://golang:1.23-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-counter binary
        working-directory: ./performance-tests/test/src
        run: xk6 build --with github.com/avitalique/xk6-file@latest

      - name: Run k6 to generate tokens
        working-directory: ./performance-tests/test/src
        run: ./k6 run generate-tokens.js
        env:
          env: ${{ secrets.YTENVIRONMENT }}
          tokengenuser: ${{ secrets.TOKENGENUSER }}
          tokengenuserpwd: ${{ secrets.TOKENGENPWD }}
          limit: 10

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run local k6 test
        uses: grafana/run-k6-action@v1  
        with: 
          path: performance-tests/test/src/test.js
          flags: --vus=10 --duration=1m
        env:
          K6_WEB_DASHBOARD: true 
          K6_WEB_DASHBOARD_EXPORT: html-report.html
          serviceowner: ${{ secrets.OWNER }}

      - name: Upload summary html report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: summary-html
          path: summary.html
      - name: Upload extended html report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: extended-html
          path: html-report.html

      - name: Upload HTML report to Azure
        if: always()
        shell: sh
        run: |
            REPORT_DIR='taxreports'
            azcopy cp --recursive "performance-tests/test/src/*.html" "https://altinnloadtests.blob.core.windows.net/\$web/$REPORT_DIR"
            echo "::Link to test results summary: title=HTML report url::https://altinnloadtests.z1.web.core.windows.net/$REPORT_DIR/summary.html"
            echo "::Link to test results extended: title=HTML report url::https://altinnloadtests.z1.web.core.windows.net/$REPORT_DIR/html-report.html"
        env:
            AZCOPY_AUTO_LOGIN_TYPE: SPN
            AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
            AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
            AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}

