name: taxreport loadtest smoketest

on:
  push:
    branches:
      - '**'
    paths:
      - performance-tests/t3search/**
      - .github/workflows/t3search-loadtest-push.yml

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go  
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-counter binary
        working-directory: ./performance-tests/tax-report/src
        run: xk6 build --with github.com/avitalique/xk6-file@latest

      - name: Run k6 to generate tokens
        working-directory: ./performance-tests/tax-report/src
        run: ./k6 run ../../generate-tokens/src/generate-tokens.js
        env:
          env: ${{ secrets.YTENVIRONMENT }}
          tokengenuser: ${{ secrets.TOKENGENUSER }}
          tokengenuserpwd: ${{ secrets.TOKENGENPWD }}
          limit: 1

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run local k6 test
        uses: grafana/run-k6-action@v1  
        with: 
          path: performance-tests/t3search/src/t3search.js
          flags: --vus=1 --iterations=1
        env:
          subscription_key: ${{ secrets.SUBSCRIPTION_KEY }}


