name: taxreport loadtest smoketest

on:
  push:
    branches:
      - '**'
    paths:
      - performance-tests/tax-report/**
      - .github/workflows/taxreport-loadtest-push.yml

jobs:
  run-taxreport-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Generate tokens
        working-directory: ./performance-tests/tax-report/src
        run: ../../generate-tokens/src/generate-tokens.sh ../../generate-tokens/src 1
        env:
          API_ENVIRONMENT: ${{ secrets.YTENVIRONMENT }}
          TOKEN_GENERATOR_USERNAME: ${{ secrets.TOKENGENUSER }}
          TOKEN_GENERATOR_PASSWORD: ${{ secrets.TOKENGENPWD }}

      - name: Setup K6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1

      - name: Run local k6 test
        uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d # v1  
        with: 
          path: performance-tests/tax-report/src/tax-report.js
          flags: --vus=1 --iterations=1
        env:
          serviceowner: ${{ secrets.OWNER }}


